import { createMcpHandler } from "agents/mcp";
import { createServer } from "./mcp/server.js";

// MCP_TOKEN is a secret set via `wrangler secret put MCP_TOKEN` (or in
// .dev.vars for local). Secrets aren't in the ambient Env type generated by
// `wrangler types` until set.
type WorkerEnv = Env & { MCP_TOKEN?: string };

const CORS_HEADERS: Record<string, string> = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, mcp-session-id, mcp-protocol-version",
  "Access-Control-Expose-Headers": "mcp-session-id",
  "Access-Control-Max-Age": "86400",
};

export default {
  async fetch(request, env, ctx): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === "/mcp") {
      // CORS preflight — must respond before the auth check, since the
      // browser sends OPTIONS without the Authorization header.
      if (request.method === "OPTIONS") {
        return new Response(null, { status: 204, headers: CORS_HEADERS });
      }

      const authResponse = checkAuth(request, env);
      if (authResponse) return withCors(authResponse);

      const server = createServer(env);
      const response = await createMcpHandler(server)(request, env, ctx);
      return withCors(response);
    }

    return env.ASSETS.fetch(request);
  },
} satisfies ExportedHandler<WorkerEnv>;

function checkAuth(request: Request, env: WorkerEnv): Response | null {
  if (!env.MCP_TOKEN) {
    return new Response("MCP_TOKEN secret is not configured on the Worker.", {
      status: 500,
    });
  }
  const header = request.headers.get("Authorization");
  const expected = `Bearer ${env.MCP_TOKEN}`;
  if (header !== expected) {
    return new Response("Unauthorized", { status: 401 });
  }
  return null;
}

// Clone the response so we can attach CORS headers. The headers on responses
// returned from createMcpHandler aren't always mutable in place.
function withCors(response: Response): Response {
  const headers = new Headers(response.headers);
  for (const [key, value] of Object.entries(CORS_HEADERS)) {
    headers.set(key, value);
  }
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}
