import { createMcpHandler } from "agents/mcp";
import { createServer } from "./mcp/server.js";

// MCP_TOKEN is a secret set via `wrangler secret put MCP_TOKEN`. Secrets are
// not in the ambient Env type generated by `wrangler types` until set.
type WorkerEnv = Env & { MCP_TOKEN?: string };

export default {
  async fetch(request, env, ctx): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === "/mcp") {
      const authResponse = checkAuth(request, env);
      if (authResponse) return authResponse;

      const server = createServer(env);
      return createMcpHandler(server)(request, env, ctx);
    }

    return env.ASSETS.fetch(request);
  },
} satisfies ExportedHandler<WorkerEnv>;

function checkAuth(request: Request, env: WorkerEnv): Response | null {
  if (!env.MCP_TOKEN) {
    return new Response("MCP_TOKEN secret is not configured on the Worker.", {
      status: 500,
    });
  }
  const header = request.headers.get("Authorization");
  const expected = `Bearer ${env.MCP_TOKEN}`;
  if (header !== expected) {
    return new Response("Unauthorized", { status: 401 });
  }
  return null;
}
